### PR TITLE
Remove trailing whitespace and convert tabs to space

### PR DESCRIPTION
**Pull request by jdumas**
A lot of files have a mix of tabs and space, so converting tabs to 8-spaces in bulk. Similarly I trimmed any trailing whitespace.

You can [ignore whitespace](https://github.blog/2018-05-01-ignore-white-space-in-code-review/) to make sure I've only edited whitespaces in this PR.

Ideally we'd have clang-format enabled in github action to make sure files are consistently formatted, but I guess that's a topic for another time :)

### CODE REVIEW

**Comment by BrunoLevy** [comment]
Hi Jeremie,
Finally I have written a script that converts tabs and trims trailing whitespace, and applied it to whole sourcetree (and I have updated my editor config so that it removes all trailing whitespaces each time it saves a file). 
I have just pushed a new version.

**Comment by jdumas** [comment]
Thanks!

**Comment by BrunoLevy** [comment]
Now working on a script that will in addition reindent all sources. It is on its way...

**Comment by jdumas** [comment]
Or adopt clang-format and stop worrying about these details :) ([this repo](https://github.com/djc/clang-format-find) has a script to find the clang-format settings that best match your existing style, maybe this could be adapted to find the config you like the best).

**Pull request closed without merging**
