### PR TITLE
Atomics refactor to use std::atomics

### PR DESCRIPTION
**Pull request by kevinbentley**
Added support for aarch64 architectures. To do so required refactoring the uses of atomics.

This replaces the architecture specific atomics and spinlocks to use std::atomics. It passes all of the same tests that pass on the main branch. I have done basic performance comparisons using the tests and they are nearly identical on x64 and mac. I haven't compared android or arm32.

### CODE REVIEW

**Comment by BrunoLevy** [comment]
Fantastic ! I'll look at it and merge it as soon as I can find time. Many thanks !

**Comment by BrunoLevy** [comment]
Awesome ! Thank you very much. This will be included in v1.8.8

**Comment by BrunoLevy** [comment]
Argh, breaks compilation on different platforms, will revert back previous implementation and re-schedule it for v1.8.9....

**Comment by BrunoLevy** [comment]
Now looking carefully, trying to fix it. Will keep you updated.

**Comment by BrunoLevy** [comment]
Hi, I have done a couple of fixes (repo is up to date), now all the non-regression tests pass for all my platform. Would you test it ?

**Comment by kevinbentley** [comment]
Yes, I'll get back to you ASAP.

**Pull request merged**
